### PR TITLE
Update github actions

### PR DESCRIPTION
**Pull request by yewtc**
I was assigned this repo as part of the pull request club.  I'm going to actually do 2 pull requests.  This one is a "meta" the "meta" pull request. Mainly updating the github actions to be current versions, to  remove some warnings. I had to do a perltidy - on script/perlvars and App/perlvars.pm  - which I don't understand,  but anyway it was needed. I also added the work flow dispatch option to enable running from within github. There is still a warning, but that is from perl-actions/install-with-cpm@v1 about set-output.  I mention it here as I see that you are one of contributors to that repo and there is an open issue for it.

### CODE REVIEW

**Comment by oalders** [comment]
Thanks for this @yewtc! I'm going to close and re-open to kick off a CI build.

**Comment by oalders** [comment]
> There is still a warning, but that is from perl-actions/install-with-cpm@v1 about set-output

I'm actually not sure why that warning occurs. It's quite noisy, though. 😞

**Comment by oalders** [comment]
We've got a 5.38 failure here.

**Comment by yewtc** [comment]
See issue #4 - there's a change in perl behaviour starting with 5.37. I was going to fix the tests, but  as per the issue, I'm not sure if fixing the tests to make them pass is the correct solution. Any fix needs to be thought through. 

I'm not sure that it isn't a perl bug.

**Comment by oalders** [comment]
Right. I guess it's related to https://github.com/houseabsolute/p5-Test-Vars/issues/47 and also https://github.com/Perl/perl5/issues/20114

**Pull request closed without merging**
