### PR TITLE
Temporarily fix test failures for perl > 5.37.3

### PR DESCRIPTION
**Pull request by hakonhagland**
Temporarily fix test failures until `Test::Vars` has been updated to handle the new op codes introduced in perl 5.37.3. See https://github.com/perl-ide/App-perlvars/issues/4 and https://github.com/houseabsolute/p5-Test-Vars/issues/47 for more information.

_[[Assigned by [pullrequest.club](https://pullrequest.club/)]]_

### CODE REVIEW

**Comment by oalders** [comment]
Closing and re-opening to kick off CI.

**Comment by hakonhagland** [comment]
Ran `perltidy -b t/app-perlvars.t` and `perltidy -b t/perlvars.t` to try fix test failure for `xt/author/tidyall.t`

**Comment by hakonhagland** [comment]
@oalders Any idea why `tidyall.t` is still failing after last commit?

**Comment by oalders** [comment]
@hakonhagland do you have the latest version of `perltidy`?

**Comment by hakonhagland** [comment]
```
$ perltidy --version
This is perltidy, v20230912 
```

**Comment by hakonhagland** [comment]
I think we should use `tidyall` and not `perltidy`.

**Comment by oalders** [comment]
> I think we should use tidyall and not perltidy.

`tidyall` is just a wrapper around `perltidy`, so they will both get us to the same place. Ideally we'd be using `precious` rather than `tidyall`. It's a less problematic tool.

**Comment by hakonhagland** [comment]
Right. Anyway, I think the problem was that `perltidy` did not check `tidyall.ini` which defined the profile file as `perltidyrc`, but `perltidy` was looking for `.perltidyrc` (with a dot in front). Which it did not find, and therefore used default values instead.

**Comment by oalders** [comment]
Thanks, @hakonhagland!

**Comment by oalders** [comment]
New release has been uploaded to CPAN.

**Pull request merged**
